version: '2'

services:
    mldonkey:
        build: .
        image: huangyingw/mldonkey
        volumes:
            - ./data:/var/lib/mldonkey
        ports:
            - "0.0.0.0:4080:4080"
            - "0.0.0.0:19040:19040"
            - "0.0.0.0:19044:19044"
