version: '2'

services:
    mldonkey:
        build: .
        image: huangyingw/mldonkey
        volumes:
            - ./var/lib/mldonkey/:/var/lib/mldonkey/
        network_mode: "host"
        env_file:
            - mldonkey.env
